# Generated by Django 5.2.10 on 2026-01-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_counsellingassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounsellingAssignment',
        ),
    ]
