# Generated by Django 5.2.10 on 2026-02-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alumnichatmessage'),
        ('faculty', '0013_chatmessage'),
        ('students', '0016_studentprofile_is_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnichatmessage',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.facultyprofile'),
        ),
        migrations.AlterField(
            model_name='alumnichatmessage',
            name='sender',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ALUMNI', 'Alumni'), ('FACULTY', 'Faculty')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alumnichatmessage',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
    ]
