# Generated by Django 5.2.10 on 2026-02-11 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alumnichatmessage_faculty_and_more'),
        ('faculty', '0013_chatmessage'),
        ('students', '0016_studentprofile_is_graduated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnichatmessage',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='alumnichatmessage',
            name='sender',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ALUMNI', 'Alumni')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alumnichatmessage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
        migrations.CreateModel(
            name='AlumniFacultyChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('FACULTY', 'Faculty'), ('ALUMNI', 'Alumni')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumniprofile')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.facultyprofile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
