# Generated by Django 5.2.10 on 2026-01-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_attendance_unique_together_attendance_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'semester_no')},
            },
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=2)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.semester')),
            ],
        ),
    ]
