# Generated by Django 5.2.10 on 2026-01-28 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_semester_subjectmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('period', models.IntegerField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'date', 'period')},
            },
        ),
    ]
