# Generated by Django 5.2.10 on 2026-01-29 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_chatmessage'),
        ('students', '0005_periodattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='periodattendance',
            name='faculty',
            field=models.ForeignKey(
                default=9,  # ✅ FIXED HERE
                on_delete=django.db.models.deletion.CASCADE,
                to='faculty.facultyprofile'
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='periodattendance',
            unique_together={('student', 'faculty', 'date', 'period')},
        ),
    ]
