# Generated by Django 5.2.10 on 2026-01-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_subject_midmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='mobileno',
            field=models.CharField(default=9701895032, max_length=10),
            preserve_default=False,
        ),
    ]
