# Generated by Django 5.2.10 on 2026-02-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentprofile_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='midmark',
            name='actual_assignment',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='midmark',
            name='actual_internal',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='midmark',
            name='actual_online',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='midmark',
            name='online_marks',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
