# Generated by Django 5.2.10 on 2026-02-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_midmark_actual_assignment_midmark_actual_internal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midmark',
            old_name='online_marks',
            new_name='online_quiz',
        ),
    ]
