# Generated by Django 5.2.10 on 2026-02-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_rename_online_marks_midmark_online_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='mobileno',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.CharField(default=20, max_length=30),
            preserve_default=False,
        ),
    ]
