# Generated by Django 5.2.10 on 2026-02-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_studentprofile_mobileno_studentprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='acquired_credits',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='actual_credits',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='result',
            field=models.CharField(default=6, max_length=10),
            preserve_default=False,
        ),
    ]
