# Generated by Django 5.2.10 on 2026-02-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_studentacademicrisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentacademicrisk',
            name='explanation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
