# Generated by Django 5.2.10 on 2026-02-02 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_studentacademicrisk_explanation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentacademicrisk',
            options={'ordering': ['-risk_score'], 'verbose_name': 'Student Academic Risk', 'verbose_name_plural': 'Student Academic Risks'},
        ),
        migrations.AlterField(
            model_name='studentacademicrisk',
            name='explanation',
            field=models.JSONField(blank=True, help_text='Explainable AI (SHAP) feature contributions', null=True),
        ),
        migrations.AlterField(
            model_name='studentacademicrisk',
            name='risk_score',
            field=models.FloatField(help_text='Normalized risk score (0 to 1)'),
        ),
        migrations.AlterField(
            model_name='studentacademicrisk',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_risk', to='students.studentprofile'),
        ),
    ]
