# Generated by Django 5.2.10 on 2026-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_studentacademicrisk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
    ]
