# Generated by Django 5.2.10 on 2026-02-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_studentprofile_is_graduated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='acquired_credits',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='actual_credits',
            field=models.FloatField(),
        ),
    ]
