# Generated by Django 5.2.10 on 2026-02-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_semester_acquired_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmark',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
