# Generated by Django 5.2.10 on 2026-02-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_subjectmark_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
